 <table>
     <tr>
         <td></td>
         <td>{__('Operations')}</td>
         <td>{__('Cumac')}</td>
         <td>{__('Surfaces')}</td>
     </tr>
     <tr>
         <td>101</td>
         <td></td>
         <td></td>
         <td></td>
     </tr>
     <tr>
         <td>102</td>
         <td></td>
         <td></td>
         <td></td>
     </tr>
     <tr>
         <td>103</td>
         <td></td>
         <td></td>
         <td></td>
     </tr>
     <tr>
         <td></td>
         <td></td>
         <td></td>
         <td>{__('Total')}</td>
     </tr>
</tbale>
