'<td>{__('Answer')}'+
'</td>'+
'<td>'+                        
    '<textarea class="formfields Request" id="#0#" disabled="disabled" name="answer"></textarea>'+
    '<div>'+
        '{__('Cols')}<input type="text" class="formfields Answer Text" size="5" name="cols" id="#0#" value=""/>'+                                                      
        '{__('Rows')}<input type="text" class="formfields Answer Text" size="5" name="rows" id="#0#" value=""/>'+
        '{__('Min length')}<input class="formfields Answer" size="5" name="min_length" value=""/>'+                                    
        '{__('Max length')}<input class="formfields Answer" size="5" name="max_length" value=""/>'+
        '{__('Required')}<input type="checkbox" class="formfields Answer" name="required"/>'+
    '</div>'+                        
'</td>'+
'<td>'+
    '<a href="#" class="Survey-Actions" id="#0#" name="Delete"><i class=" fa fa-trash" style=" margin-left: 10px;"></i></a>'+
'</td>'                  
           