'<td>{__('Answer')}'+
'</td>'+
'<td>'+                        
    'XXX'+   
    '{__('Size')}<input type="text" class="formfields Answer" id="#0#" size="5" name="size" value=""/>'+
    '{__('Required')}<input type="checkbox" class="formfields Answer" name="required"/>'+
    '{__('Multiple')}<input type="checkbox" class="formfields Answer" name="multiple"/>'+
'</td>'+
'<td>'+
    '<a href="#" class="Survey-Actions" id="#0#" name="Delete"><i class=" fa fa-trash" style=" margin-left: 10px;"></i></a>'+
'</td>'
       
