'<td>{__('Answer')}'+
'</td>'+
'<td>'+                        
    '<input class="formfields" disabled="disabled" id="#0#" size="40" name="request" value=""/>'+
    '<div>'+
        '{__('Size')}<input type="text" class="formfields Answer Size" id="#0#" size="5" name="size" value=""/>'+
        '{__('Min length')}<input class="formfields Answer" size="5" name="min_length" value=""/>'+                                    
        '{__('Max length')}<input class="formfields Answer" size="5" name="max_length" value=""/>'+
        '{__('Required')}<input type="checkbox" class="formfields Answer" name="required"/>'+
    '</div>'+                        
'</td>'+
'<td>'+
    '<a href="#" class="Survey-Actions" id="#0#" name="Delete"><i class=" fa fa-trash" style=" margin-left: 10px;"></i></a>'+
'</td>'                  
           