<?php

/*
 * Generated by SuperAdmin Generator date : 07/06/13 10:57:11
 */
 
class customers_meetings_ajaxRecycleMeetingAction extends mfAction {
    
   
    function execute(mfWebRequest $request) {      
      $messages = mfMessages::getInstance();
      try 
      {       
         $item=new CustomerMeeting($request->getPostParameter('Meeting'));
         if ($item->isLoaded())
         {    
            $item->set('status','ACTIVE');
            $item->save();
            $item->getCustomer()->enable();
            $item->setComments($this->getUser(), 'recycle');
            $response = array("action"=>"RecycleMeeting",
                              "id" =>$item->get('id'),                             
                          );
         }    
      } 
      catch (mfException $e) {
           $messages->addError($e);
      }
      return $messages->hasErrors()?array("error"=>$messages->getDecodedErrors()):$response;
    }

}

