<?php

/*
 * Generated by SuperAdmin Generator date : 24/04/13 15:45:29
 */
 
class customers_meetings_ajaxDeleteCampaignAction extends mfAction {
    
    
    
    function execute(mfWebRequest $request) {      
      $messages = mfMessages::getInstance();   
      try 
      {          
          $item=new mfValidatorInteger();
          $id=$item->isValid($request->getPostParameter('CustomerMeetingCampaign'));          
          $item= new CustomerMeetingCampaign($id);  
          if ($item->isLoaded())
          {    
            $item->delete();              
            $response = array("action"=>"DeleteCampaign","id" =>$id,"info"=>__("Campaign [%s] has been deleted.",$item->get('meta_title')));
          }
      } 
      catch (mfException $e) {
          $messages->addError($e);
      }
      return $messages->hasMessages('error')?array("error"=>$messages->getDecodedErrors()):$response;
    }
}

