<?php

/*
 * Generated by SuperAdmin Generator date : 24/04/13 15:45:29
 */
 
class customers_meetings_ajaxDeletesStatusCallAction extends mfAction {
    
   
    
    function execute(mfWebRequest $request) {      
      $messages = mfMessages::getInstance();   
      try 
      {          
          $validator=new mfValidatorSchemaForEach(new mfValidatorInteger(),count($request->getPostParameter('selection')));
          $validator->isValid($request->getPostParameter('selection'));
          $statuses= new CustomerMeetingStatusCallCollection($request->getPostParameter('selection'));
          $statuses->delete();                              
          $response = array("action"=>"DeletesStatusCall","info"=>__("Status has been deleted."),"parameters" =>$request->getPostParameter('selection'));
      } 
      catch (mfException $e) {
          $messages->addError($e);
      }
      return $messages->hasMessages('error')?array("error"=>$messages->getDecodedErrors()):$response;
    }
}

