<?php

/*
 * Generated by SuperAdmin Generator date : 24/04/13 15:45:29
 */
 
class customers_meetings_ajaxCallbacksAction extends mfAction {
    
   
    
    function execute(mfWebRequest $request) {      
      $messages = mfMessages::getInstance();   
      try 
      {           
          $settings=CustomerMeetingSettings::load();          
          $this->scheduler_time=$settings->getCallBackTimeScheduler(); // seconds => ms
          $this->callbacks=CustomerMeetingUtils::getCallbacks($this->getUser());
      } 
      catch (mfException $e) {
          $messages->addError($e);
      }      
    }
}

