<?php

/*
 * Generated by SuperAdmin Generator date : 07/06/13 10:57:11
 */
 
class customers_meetings_ajaxDeleteMeetingProductAction extends mfAction {
    
   
    
    function execute(mfWebRequest $request) {      
      $messages = mfMessages::getInstance();
      try 
      {        
         $item=new CustomerMeetingProduct($request->getPostParameter('MeetingProduct'));
         if ($item->isLoaded())
         {    
            $item->set('status','DELETE');           
            $item->save();
            $response = array("action"=>"DeleteMeetingProduct",
                              "info"=>__('Product has been deleted.'),
                              "id" =>$item->get('id')
                          );
         }    
      } 
      catch (mfException $e) {
           $messages->addError($e);
      }
      return $messages->hasErrors()?array("error"=>$messages->getDecodedErrors()):$response;
    }

}

