<?php

/*
 * Generated by SuperAdmin Generator date : 24/04/13 15:45:29
 */
 
class products_items_ajaxDeleteItemAction extends mfAction {
    
    
    
    function execute(mfWebRequest $request) {      
      $messages = mfMessages::getInstance();   
      try 
      {                                
          $item= new ProductItem($request->getPostParameter('ProductItem'));
          if ($item->isLoaded())
          {    
            $item->delete();              
            $response = array("action"=>"DeleteItem",
                              "id" =>$item->get('id'),
                              "info"=>__("Product item [%s] has been deleted.",$item->get('reference')));
          }
      } 
      catch (mfException $e) {
          $messages->addError($e);
      }
      return $messages->hasMessages('error')?array("error"=>$messages->getDecodedErrors()):$response;
    }
}

