<?php

/*
 * Generated by SuperAdmin Generator date : 07/06/13 10:57:11
 */
 
class products_ajaxRecycleProductAction extends mfAction {
    
    const SITE_NAMESPACE = 'system/site';
    
    function execute(mfWebRequest $request) {      
      $messages = mfMessages::getInstance();
      try 
      {
         $site=$this->getUser()->getStorage()->read(self::SITE_NAMESPACE);
         if (!$site)
            return "";
          $item=new mfValidatorInteger();
          $id=$item->isValid($request->getPostParameter('Product'));          
          $item= new Product($id,$site);           
          $item->enable();              
          $response = array("action"=>"RecyclingProduct","id" =>$id,"info"=>__("Product [%s] has been recycled.",$item->get('meta_title')));  
      } 
      catch (mfException $e) {
           $messages->addError($e);
      }
      return $messages->hasErrors()?array("error"=>$messages->getDecodedErrors()):$response;
    }

}

