<?php

/*
 * Generated by SuperAdmin Generator date : 28/04/13 21:56:09
 */
 
require_once dirname(__FILE__)."/ajaxListPartialTaxesAction.class.php";

class products_ajaxListTaxesAction extends products_ajaxListPartialTaxesAction {
    

}