<?php

/*
 * Generated by SuperAdmin Generator date : 05/06/13 23:04:58
 */

 class CustomerMeetingBaseForm extends mfFormSite {
 
   // All fields excepted foreign keys
     function __construct($defaults = array(),$site = null) {
         parent::__construct($defaults,array(), $site);
     }
   
    function configure()
    {
        $this->setValidators(array(
            "id"=>new mfValidatorInteger(),  
            'customer_id'=> new ObjectExistsValidator('Customer',array(),$this->getSite()),
            'in_at'=>new mfValidatorI18nDateTime(array("required"=>false,"date_format"=>"a","scale_minute"=>15,"scale_hour"=>1,"hour_min"=>6,"hour_max"=>23)),        
            'see_with_mr'=>new mfValidatorBoolean(array('true'=>'YES','false'=>'NO','empty_value'=>'NO')),
            'see_with_mrs'=>new mfValidatorBoolean(array('true'=>'YES','false'=>'NO','empty_value'=>'NO')),
           // 'see_both'=>new mfValidatorBoolean(array('true'=>'YES','false'=>'NO','empty_value'=>'NO')),            
            'remarks'=>new mfValidatorString(array("required"=>false)),
            'sale_comments'=>new mfValidatorString(array("required"=>false)),           
            ) 
        );
    }
    
  
}


