<?php

/*
 * Generated by SuperAdmin Generator date : 24/04/13 15:45:29
 */
 
class partners_ajaxDeletePartnerContactAction extends mfAction {
    
    
    
    function execute(mfWebRequest $request) {      
      $messages = mfMessages::getInstance();   
      try 
      {
          $site=$this->getUser()->getStorage()->read(self::SITE_NAMESPACE);        
          $item=new mfValidatorInteger();
          $id=$item->isValid($request->getPostParameter('PartnerContact'));          
          $item= new PartnerContact($id);           
          $item->delete();              
          $response = array("action"=>"deletePartnerContact","id" =>$id,"info"=>__("Partner has been deleted."));
      } 
      catch (mfException $e) {
          $messages->addError($e);
      }
      return $messages->hasMessages('error')?array("error"=>$messages->getDecodedErrors()):$response;
    }
}

