<?php

/*
 * Generated by SuperAdmin Generator date : 05/06/13 23:04:58
 */

 class EmulatorForm extends mfFormSite {
 
    function __construct($defaults = array(), $site = null) {
        parent::__construct($defaults,  array(), $site);
    }
    
    
    function configure()
    {
        $this->setValidators(array(
            "url"=>new mfValidatorString(array("max_length"=>300,"required"=>true)),                                                                             
            "command"=>new mfValidatorString(array("max_length"=>64,"required"=>true)),                                                                             
            "post"=>new mfValidatorJSON(array("max_length"=>64,"required"=>true)),                                                                             
            ) 
        );
    }
    
 
}


