<?php

class Browser { 
	public function Browser($userAgent = "");
	public function reset();
	function isBrowser($browserName);
	public function getBrowser();
	public function setBrowser($browser);
	public function getPlatform();
	public function setPlatform($platform);
	public function getVersion();
	public function setVersion($version);
	public function getAolVersion();
	public function setAolVersion($version);
	public function isAol();
	public function isMobile();
	public function isTablet();
	public function isRobot();
	public function isFacebook();
	public function setAol($isAol);
	protected function setMobile($value = true);
	protected function setTablet($value = true);
	protected function setRobot($value = true);
	protected function setFacebook($value = true);
	public function getUserAgent();
	public function setUserAgent($agent_string);
	public function isChromeFrame();
	public function __toString();
	protected function determine();
	protected function checkBrowsers();
	protected function checkBrowserBlackBerry();
	protected function checkForAol();
	protected function checkBrowserGoogleBot();
	protected function checkBrowserMSNBot();
	protected function checkBrowserW3CValidator();
	protected function checkBrowserSlurp();
	protected function checkBrowserInternetExplorer();
	protected function checkBrowserOpera();
	protected function checkBrowserChrome();
	protected function checkBrowserWebTv();
	protected function checkBrowserNetPositive();
	protected function checkBrowserGaleon();
	protected function checkBrowserKonqueror();
	protected function checkBrowserIcab();
	protected function checkBrowserOmniWeb();
	protected function checkBrowserPhoenix();
	protected function checkBrowserFirebird();
	protected function checkBrowserNetscapeNavigator9Plus();
	protected function checkBrowserShiretoko();
	protected function checkBrowserIceCat();
	protected function checkBrowserNokia();
	protected function checkBrowserFirefox();
	protected function checkBrowserIceweasel();
	protected function checkBrowserMozilla();
	protected function checkBrowserLynx();
	protected function checkBrowserAmaya();
	protected function checkBrowserSafari();
	protected function checkFacebookExternalHit();
	protected function checkForFacebookIos();
	protected function getSafariVersionOnIos();
	protected function getChromeVersionOnIos();
	protected function checkBrowseriPhone();
	protected function checkBrowseriPad();
	protected function checkBrowseriPod();
	protected function checkBrowserAndroid();
	protected function checkPlatform();
}
