<?php

/*
 * Generated by SuperAdmin Generator date : 05/06/13 23:04:58
 */

 class UserTeamBaseForm extends mfFormSite {
 
    function __construct($defaults = array(), $site = null) {
        parent::__construct($defaults,  array(), $site);
    }
    
    
    function configure()
    {
        $this->setValidators(array(
            "id"=>new mfValidatorInteger(),                                    
            "name"=>new mfValidatorString(array("max_length"=>64)),                                                                             
            ) 
        );
    }
    
 
}


