'<td class="label">{__('Answer')}'+
'</td>'+
'<td>'+   
    '<div class="Answer-info">'+
      {* '<label>{__('Size')} : </label><input type="text" class="formfields Answer" id="#0#" size="5" name="size" value=""/>'+ *}
       '<label>{__('Required')} : </label><input type="checkbox" class="formfields Answer" name="required"/>'+
       '<label>{__('Multiple')} : </label><input type="checkbox" class="formfields Answer" name="multiple"/>'+
   '</div>'+ 
'</td>'+  
'<td>'+
    '<a href="#" class="Survey-Actions" id="#0#" name="Delete"><i class=" fa fa-trash fa-2x" style=" margin-left: 10px;"></i></a>'+
'</td>'