'<td class="label">{__('Answer')}'+
'</td>'+
 '<td>'+ 
'</td>'+  
'<td>'+                        
    '<textarea class="formfields Request" style="min-width: 344px;" id="#0#" disabled="disabled" name="answer"></textarea>'+
    '<div class="Answer-info-text">'+
        '<label>{__('Cols')} : </label><input type="text" class="formfields Answer Text" size="5" name="cols" id="#0#" value=""/>'+                                                      
        '<label>{__('Rows')} : </label><input type="text" class="formfields Answer Text" size="5" name="rows" id="#0#" value=""/>'+
        '<label>{__('Min length')} : </label><input class="formfields Answer" size="5" name="min_length" value=""/>'+                                    
        '<label>{__('Max length')} : </label><input class="formfields Answer" size="5" name="max_length" value=""/>'+
        '<label>{__('Required')} : </label><input type="checkbox" class="formfields Answer" name="required"/>'+
    '</div>'+                        
'</td>'+
'<td style="width: 200px ; text-align: right" >'+
    '<a href="#" class="Survey-Actions" id="#0#" name="Delete"><i class=" fa fa-trash fa-2x" style=" margin-left: 10px;"></i></a>'+
'</td>'                  
           