'<tr id="#0#" class="Survey-Choices-items Survey-Choices-item full-with">'+
    '<td>'+
         '<label>{__("Choice")} <span class="Survey-Choices-items-number" id="#0#">#1#</span></label><input id="#0#" type="text" class="Survey-Choices-Input"/>'+        
    '</td>'+
    '<td>'+                          
         '<a href="#" class="Survey-Choices-Action-Delete" id="#0#" name="Delete"><i class=" fa fa-trash" style=" margin-right:10px;"></i></a>'+                        
    '</td>'+
'</tr>'
       
