'<td class="label">{__('Answer')}'+
'</td>'+
    '<td>'+
    '</td>'+
    '<td>'+  
        '<input class="formfields" disabled="disabled" id="#0#" size="40" name="request" value=""/>'+
        '<div class="Answer-info">'+
        '<label>{__('Size')} : </label><input type="text" class="formfields Answer Size" id="#0#" size="5" name="size" value=""/>'+
        '<label>{__('Min length')} : </label><input class="formfields Answer" size="5" name="min_length" value=""/>'+                                    
        '<label>{__('Max length')} : </label><input class="formfields Answer" size="5" name="max_length" value=""/>'+
        '<label>{__('Required')} : </label><input type="checkbox" class="formfields Answer" name="required"/>'+
    '</div>'+ 
   '</td>'+

'<td style="width: 200px ; text-align: right" >'+
    '<a href="#" class="Survey-Actions" id="#0#" name="Delete"><i class=" fa fa-trash fa-2x" style=" margin-left: 10px;"></i></a>'+
'</td>'                  
           