<?php

/*
 * Generated by SuperAdmin Generator date : 07/06/13 10:57:11
 */
 
class customers_contracts_ajaxDeleteContractProductAction extends mfAction {
    
    
    
    function execute(mfWebRequest $request) {      
      $messages = mfMessages::getInstance();
      try 
      {        
         $item=new CustomerContractProduct($request->getPostParameter('ContractProduct'));
         if ($item->isLoaded())
         {    
            $item->delete();           
            $response = array("action"=>"DeleteContractProduct",
                              "info"=>__('Product has been deleted.'),
                              "id" =>$item->get('id')
                          );
         }    
      } 
      catch (mfException $e) {
           $messages->addError($e);
      }
      return $messages->hasErrors()?array("error"=>$messages->getDecodedErrors()):$response;
    }

}

