<?php

/*
 * Generated by SuperAdmin Generator date : 07/06/13 10:57:11
 */
 
class customers_contracts_ajaxCreateContributorAction extends mfAction {
    
    
    
    function execute(mfWebRequest $request) {      
      $messages = mfMessages::getInstance();
      try 
      {         
         $item=new CustomerContract($request->getPostParameter('Contract'));
         if ($item->isLoaded())
         {    
            if ($item->hasContributors())
                throw new mfException(__("Contract has already contributors."));
            $item->createContributors();           
            $response = array("info"=>__("Contributors created."),
                              
                          );
         }    
      } 
      catch (mfException $e) {
           $messages->addError($e);
      }
      return $messages->hasErrors()?array("error"=>$messages->getDecodedErrors()):$response;
    }

}

