<?php

/*
 * Generated by SuperAdmin Generator date : 25/03/13 16:38:07
 */
 
require_once dirname(__FILE__)."/ajaxListPartialModuleManagerAction.class.php";

class modules_manager_listModuleManagerAction extends modules_manager_ajaxListPartialModuleManagerAction {
    

}

