<?php

/*
 * Generated by SuperAdmin Generator date : 25/03/13 16:38:07
 */
 
require_once dirname(__FILE__)."/ajaxListPartialModuleManagerAdminAction.class.php";

class modules_manager_listModuleManagerAdminAction extends modules_manager_ajaxListPartialModuleManagerAdminAction {
    

}

