<?php

/*
 * Generated by SuperAdmin Generator date : 28/04/13 21:56:09
 */

 class TaxBaseForm extends mfForm {
 
   // All fields excepted foreign keys
   
    function configure()
    {
        $this->setValidators(array(
            "id"=>new mfValidatorInteger(),                              
            "rate"=>new mfValidatorI18nPourcentage(),            
            "description"=>new mfValidatorString(array("max_length"=>"255",)),            
       //     "is_active"=>new mfValidatorChoice(array("choices"=>array("YES","NO"),)),            
                        
                        
            ) 
        );
    }
    
 
}


