<?php

/*
 * Generated by SuperAdmin Generator date : 07/04/13 00:25:08
 */
 
class modules_manager_ajaxIsActiveChangesModuleManagerAction extends mfAction {
    
    const SITE_NAMESPACE = 'system/site';
    
    
    
    function execute(mfWebRequest $request) { 
      $messages = mfMessages::getInstance();
      try 
      {
          $site=$this->getUser()->getStorage()->read(self::SITE_NAMESPACE); 
          if (!$site)  
               throw new mfException(__("thanks to select a site"));  
          $form=new moduleManagerIsActiveChangesForm($request->getPostParameter('moduleManagers'));
          $form->bind($request->getPostParameter('moduleManagers'));
          if ($form->isValid())
          {    
            $items= new moduleManagerCollection($form->getValue('moduleManagers'),$site);   
            $items->save();
            $items->removeConfigCache();
       //     $this->getEventDispather()->notify(new mfEvent($items, 'moduleManagers.change','change')); 
            $response = array("action"=>"IsActiveChangesModuleManager",
                            "state" =>(string)$form['value'],
                            "selection" =>$form->getValue('selection')
                           );
          }
      } 
      catch (mfException $e) {
          $messages->addError($e);
      }
      return $messages->hasErrors()?array("error"=>$messages->getDecodedErrors()):$response;
    }

}

