<?php

/*
 * Generated by generator date : 23/03/13 21:59:25
 */
 
class modules_manager_ajaxBuildModuleManagerAction extends mfAction {
    
    const SITE_NAMESPACE = 'system/site';
    
    function execute(mfWebRequest $request) { 
    
      $messages = mfMessages::getInstance();
      try 
      {
         $site=$this->getUser()->getStorage()->read(self::SITE_NAMESPACE);  
       //  moduleManagerUtils::getModulesFromSuperadmin($site);
          moduleManagerUtils::buildModulesList($site);
         $response=array("info"=>__('modules structure has been built.'));
          
         // $response = array("action"=>"buildModuleAdmin");
      } 
      catch (mfException $e) {
          $messages->addError($e);
      }
      return $messages->hasMessages('error')?array("error"=>$messages->getDecodedErrors()):$response;
    }

}

