<?php

/*
 * Generated by SuperAdmin Generator date : 24/04/13 15:45:29
 */
 
class customers_meetings_forms_ajaxProcessUpdateMeetingFormAction extends mfAction {
    
    const SITE_NAMESPACE = 'system/site';
    
    function execute(mfWebRequest $request) {      
      $messages = mfMessages::getInstance();   
      try 
      {
          $site=$this->getUser()->getStorage()->read(self::SITE_NAMESPACE);
          if (!$site) 
              throw new mfException(__("thanks to select a site"));    
          $validator=new mfValidatorInteger();
          $id=$validator->isValid($request->getPostParameter('Meeting'));          
          $meeting=new CustomerMeeting($id,$site);
          if ($meeting->isNotLoaded())
                throw new mfException(__("Meeting is invalid."));  
          CustomerMeetingFormUtils::processUpdate($meeting);           
          $response = array("action"=>"ProcessUpdateForm","id" =>$id,"info"=>__("Form has been processed."));        
      } 
      catch (mfException $e) {
          $messages->addError($e);
      }
      return $messages->hasMessages('error')?array("error"=>$messages->getDecodedErrors()):$response;
    }
}

