<?php

/*
 * Generated by SuperAdmin Generator date : 24/04/13 15:45:29
 */
 
class users_ajaxDeleteAttributionI18nAction extends mfAction {
    
    
    
    function execute(mfWebRequest $request) {      
      $messages = mfMessages::getInstance();   
      try 
      { 
          $item=new mfValidatorInteger();
          $id=$item->isValid($request->getPostParameter('UserAttributionI18n'));          
          $item= new UserAttributionI18n($id);           
          $item->delete();              
          $response = array("action"=>"deleteAttributionI18n","id" =>$id,"info"=>__("Attribution has been deleted."));
      } 
      catch (mfException $e) {
          $messages->addError($e);
      }
      return $messages->hasMessages('error')?array("error"=>$messages->getDecodedErrors()):$response;
    }
}

